### ISSUE TITLE
not working on Android 7.0 version

### ISSUE THREAD

**Issue by MatanTubul** [yatt-ze/DirtyCowAndroid#3]
i executed the code and all is run except in the end i get after: "adb shell /system/bin/run-as command:"
run-as: Usage:
    run-as <package-name> [--user <uid>] <command> [<args>]

**Comment by yatt-ze** [comment]
I get this as well on android 6 (emui4), the run-as executable is not getting overwritten, I'm not working on this anymore though I will review push / pull requests

**Comment by yatt-ze** [comment]
Closing issue, no fixes have been submitted, and can't be bother to fix myself
